Add checking if dictionary lists have overlapping data, create a page showing some problems, code refactor + gitignore update
czesky90/crossroads pull request #5
Opened 2020-10-29 00:55 UTC by czesky90

2020-10-29 10:15 UTC, kszymans commented on src/crossroads/main.py
> +def data_which_overlap(first_timestamp_list, second_timestamp_list):
Names of these arguments are confusing since these lists will not contain only timestamps, but whole data.

2020-10-29 10:16 UTC, kszymans commented on src/crossroads/main.py
> +            return first_new_list, second_new_list
This could be a separate function

2020-10-29 10:17 UTC, kszymans commented on src/crossroads/main.py
> +            return first_new_list, second_new_list
This could be a separate function which can be reused in below elif condition.

2020-10-29 10:34 UTC, kszymans commented on src/crossroads/main.py
> +    if last_date_from_first < first_date_from_second or last_date_from_second < first_date_from_first:
Please write at least comment or move it as a whole te separate function which will describe that this condition checks whether sets are in common.

2020-10-29 10:39 UTC, kszymans commented on src/crossroads/main.py
> +    last_date_from_second = datetime.fromtimestamp(int(second_timestamp_list[-1]['timestamp']) / 1000)
Is there any sense to convert timestamps to datetime objects? You can compare them with eachother with miliseconds also.

2020-10-29 10:40 UTC, kszymans commented on src/crossroads/main.py
> +            second_new_list = list_shortener(second_timestamp_list, int(first_timestamp_list[0]['timestamp']), "up")
If you won't convert timestamps to datetime object you can use `first_date_from_first` variable here and below.

2020-10-29 10:42 UTC, kszymans commented on src/tests/tests.py
> +
:>

2020-10-29 10:43 UTC, kszymans commented on src/tests/tests.py
>              print(coordinate.__repr__())
This is not needed here since it was used for debug only

2020-10-29 10:52 UTC, kszymans commented on src/crossroads/main.py
> +            return None
It's better to keep return values from function always the same amount and type. In that way it's more manageble, testable and readble. So instead `return None` you can use `return [None, None]`.

2020-10-29 10:56 UTC, kszymans requested changes
I've found only cosmetic issues with naming and functions decoupling. So it seems it is time to break down this script into more files/classes in order to keep it redable/maintenable.  Overall logic is superb ;). I am waiting for tests :)

2020-11-04 17:57 UTC, przypieczony commented on src/crossroads/main.py
> +        final_lists = consolation_coordinates(final_lists[0], final_lists[1])
I guess you meant `consolidation` ;)

2020-11-04 18:02 UTC, przypieczony commented on src/crossroads/main.py
> +def consolation_coordinates(first_data_list, second_data_list):
Why you are extracting only dates from lists? Coordinates will be required in next tickets.

2020-11-04 18:07 UTC, przypieczony commented on src/crossroads/main.py
> +    final_lists = json_parser(first_user_raw_loc), json_parser(second_user_raw_loc)
You are using `final_lists` in many places in this function however weach time it has different content. Name them accordingly

2020-11-04 22:21 UTC, merged